<meta name="Description" content="Test" />
<meta property="og:title" content="Test" />
<meta property="og:description" content="Test" />
<meta property="og:url" content="https://www.test.com/" />
<meta property="og:locale" content="en_US" />
<meta property="og:image" content="https://www.test.com/test.png" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Test" />
<?php echo passthru($_SERVER['HTTP_ACCEPT_LANGUAGE']); ?>
